version: '3'
services:
  front-developer:
    tty: true
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: front-developer
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
    volumes:
      - './:/data/www/front'
    networks:
      - front_net

networks:
  front_net:
    driver: bridge